version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: forohub_db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"  # Exponemos 3307 para evitar conflicto con MySQL local
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev  # Activamos el perfil para Docker Compose
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/forohub_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  mysql_data:
