apiVersion: apps/v1
kind: Deployment
metadata:
  name: forohub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forohub
  template:
    metadata:
      labels:
        app: forohub
    spec:
      containers:
        - name: forohub
          image: forohub-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password