apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  spring.datasource.url: jdbc:mysql://mysql-service:3306/forohub_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  spring.datasource.username: root
